#!/usr/bin/python3
#
# git am, with some extra checks to:
# * Skip empty patches that are sometimes generated by sync
# * Skip already applied patches from release branch.

import pathlib
import subprocess
import sys


def run(cmd):
    return subprocess.run(
        cmd, stderr=subprocess.STDOUT, stdout=subprocess.PIPE, universal_newlines=True
    )


for path in sys.argv[1:]:
    print("")
    print(path)
    proc = run(["diffstat", path])
    if str(proc.stdout).strip() == "0 files changed":
        print("  Skip epty patch")
        continue

    proc = run(["git", "apply", "--reverse", "--check", path])
    if proc.returncode == 0:
        print("  Skip already applied patch")
        continue

    print("  APPLY")
    proc = run(["git", "am", path])
    if proc.returncode != 0:
        print(proc.stdout)
        proc = subprocess.run(["git", "am", "--abort"], stderr=subprocess.STDOUT)
        break
